const ct = {}

ct.REGISTER_SOCMED = 'REGISTER_SOCMED';
ct.REGISTER_PHONE = 'REGISTER_PHONE';
ct.REGISTER_TOKEN = 'REGISTER_TOKEN';
ct.REGISTER_NAME = 'REGISTER_NAME';
ct.REGISTER_USERNAME = 'REGISTER_USERNAME';
ct.CLEAN_REGISTRATION = 'CLEAN_REGISTRATION';
ct.REGISTRATION = 'REGISTRATION';

export default ct;