const ct = {}

ct.REGISTER_SOCMED = 'REGISTER_SOCMED';
ct.REGISTER_PHONE = 'REGISTER_PHONE';
ct.REGISTER_TOKEN = 'REGISTER_TOKEN';
ct.REGISTER_NAME = 'REGISTER_NAME';
ct.REGISTER_USERNAME = 'REGISTER_USERNAME';
ct.CLEAN_REGISTRATION = 'CLEAN_REGISTRATION';
ct.REGISTRATION = 'REGISTRATION';
ct.SET_LOADING_STATUS = 'SET_LOADING_STATUS'; 
ct.SET_ERROR_STATUS = 'SET_ERROR_STATUS';
ct.SET_SUCCESS_STATUS = 'SET_SUCCESS_STATUS';
ct.SET_NETWORK_ERROR_STATUS = 'SET_NETWORK_ERROR_STATUS';
ct.SET_SERVER_ERROR_STATUS = 'SET_SERVER_ERROR_STATUS';
ct.SIGN_IN = 'SIGN_IN';
ct.UPDATE_USER = 'UPDATE_USER';
ct.LOG_OUT = 'LOG_OUT';
ct.GET_PRODUCTS = 'GET_PRODUCTS';
ct.GET_CATEGORIES = 'GET_CATEGORIES';
ct.GET_DELIVERY_PRICE = 'GET_DELIVERY_PRICE';
ct.CHANGE_TOTAL = 'CHANGE_TOTAL';
ct.CHANGE_CATEGORIES = 'CHANGE_CATEGORIES';
ct.TOGGLE_FAVORITE = 'TOGGLE_FAVORITE';
ct.SEARCH_PRODUCTS = 'SEARCH_PRODUCTS';
ct.CLEAR_PRODUCTS = 'CLEAR_PRODUCTS';
ct.DETAIL_PRODUCT = 'DETAIL_PRODUCT';
ct.GET_ADDRESS = 'GET_ADDRESS';
ct.GET_ADDRESS_DETAIL = 'GET_ADDRESS_DETAIL';

export default ct;