# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

def shared_pods
  pod 'MidtransCoreKit'

  pod 'MidtransKit'
end

target 'Freshbox' do
  pod 'AppCenter/Crashes', '~> 2.1.0'
  pod 'AppCenter/Analytics', '~> 2.1.0'
  pod 'AppCenterReactNativeShared', '~> 2.1.0'
  # pod 'appcenter', path: '../node_modules/appcenter/ios'
  # pod 'appcenter-analytics', path: '../node_modules/appcenter-analytics/ios'
  # pod 'appcenter-crashes', path: '../node_modules/appcenter-crashes/ios'
  # pod 'appcenter-push', path: '../node_modules/appcenter-push/ios'
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Freshbox
  pod 'GoogleSignIn'


  shared_pods


  # pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

  # pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

  platform :ios, '9.0'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
      if target.name == 'react-native-google-maps'
          target.build_configurations.each do |config|
              config.build_settings['CLANG_ENABLE_MODULES'] = 'No'
          end
      end
      if target.name == "React"
          target.remove_from_project
      end
  end
end
