# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Freshbox' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Freshbox
  pod 'GoogleSignIn'


end

post_install do |installer|
  installer.pods_project.targets.each do |target|
      if target.name == 'react-native-google-maps'
          target.build_configurations.each do |config|
              config.build_settings['CLANG_ENABLE_MODULES'] = 'No'
          end
      end
      if target.name == "React"
          target.remove_from_project
      end
  end
end
